services:
  frontend:
    container_name : nginx_container
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
  backend:
    container_name: spring_container
    build: backend/app/
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always
    volumes:
      - ./backend/app/data:/data:rw 
  db:
    container_name: db
    image: 'postgres:latest'
    secrets:
      - db-password
    environment:
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file: backend/web-bff/App/.env.dev
    environment:
      - MONGO_INTIDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INTIDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - mongo-session-data:/data/mongodb
  express:
    build: backend/web-bff/
    container_name: express-container
    env_file: backend/web-bff/App/.env.dev
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - NODE_PORT=3000
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
volumes:
  postgres-data:
  mongo-session-data:
secrets:
  db-password:
    file: backend/db/password.txt
