services:
  frontend:
    container_name : nginx_container
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./frontend/build/:/usr/share/nginx/html/build/:rw
    networks:
      docker_network:
        ipv4_address: 10.5.0.3
  db:
    container_name: db
    image: 'postgres:latest'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PGU}
      - POSTGRES_PASSWORD=${PGP}
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      docker_network:
        ipv4_address: 10.5.0.8
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      docker_network:
        ipv4_address: 10.5.0.14
volumes:
  postgres-data:
secrets:
  db-password:
    file: backend/db/password.txt
networks:
  docker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
