services:
  backend:
    container_name: spring_container
    build: backend/app/
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=${PGU}
      - SPRING_DATASOURCE_PASSWORD=${PGP}
    restart: always
    volumes:
      - ./backend/app/data:/data:rw 
  db:
    container_name: db
    image: 'postgres:latest'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PGU}
      - POSTGRES_PASSWORD=${PGP}
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file: backend/web-bff/App/.env.dev
    environment:
      - MONGO_INTIDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INTIDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - mongo-session-data:/data/mongodb
  express:
    build: backend/web-bff/
    container_name: express-container
    env_file: backend/web-bff/App/.env.dev
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - NODE_PORT=3000
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
volumes:
  postgres-data:
  mongo-session-data:

