services:
  frontend:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=pidgeon_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=swamp'
    ports:
      - '5432'
