services:
  frontend:
    container_name : nginx_container
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./frontend/build/:/usr/share/nginx/html/build/:rw
    networks:
      - docker_network
  backend:
    container_name: spring_container
    build: backend/app/
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=${PGU}
      - SPRING_DATASOURCE_PASSWORD=${PGP}
    restart: always
    volumes:
      - ./backend/app/data:/data:rw 
    networks:
      - docker_network
  db:
    container_name: db
    image: 'postgres:latest'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PGU}
      - POSTGRES_PASSWORD=${PGP}
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - docker_network
 

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
    networks:
      - docker_network
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - docker_network
volumes:
  postgres-data:
secrets:
  db-password:
    file: backend/db/password.txt
networks:
  docker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
