services:
  frontend:
    container_name : nginx_container
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
  backend:
    container_name: spring_container
    build: backend/app/
    ports:
      - 8080:8080
    environment:
        - 'POSTGRES_DB=pidegon_db'
    networks:
        - spring-postgres
  postgres:
    container_name: pg_container
    image: 'postgres:latest'
    secrets:
      - db-password
    environment:
      - 'POSTGRES_DB=pidgeon_db'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  postgres-data:
secrets:
  db-password:
    file: backend/db/password.txt
networks:
  spring-postgres:
