spring:
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/62835335-e5c4-4d22-98f2-9d5b65a06d9d/v2.0
            user-name-attribute: name
        registration:
          azure:
            provider: azure
            #client-id: "6035bfd4-22f0-437c-b76f-da729a916cbf"
            #client-secret: "fo28Q~-aLbmQvonnZtzbgtSiqYstmBWEmGPAodmx"
            client-id: 39136cda-f02f-4305-9b08-45f132bab07e
            client-secret: i1n8Q~57EDI.E2iLxzkW3Q.ixEtVIM4jwN7eDbxK
            scope:
              - openid
              - email
              - profile