name: running test with github actions
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    name: run unit tests on java 17
    steps:
      - uses: actions/checkout@master
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: gradle test
